apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      initContainers:
        - name: wait-for-service
          image: busybox:1.28
          command:
            - sh
            - -c
            - 'until nslookup nginx-init-svc; do echo waiting for service; sleep 2; done;'
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
